name: publishDebugToPgyer

on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: publishDebugToPgyer with Gradle
      run: ./gradlew publishDebugToPgyer
      env:
        KEY_PGY_API: ${{ secrets.KEY_PGY_API }}
        KEY_WEHOOK: ${{ secrets.KEY_WEHOOK }}
