name: CommentJira

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Comment on issue
      - uses: atlassian/gajira-comment@master
        with:
          issue: DC-3843
          comment: CommentJira
