name: UnitTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run jacocoTestReport
        run: ./gradlew jacocoTestReport
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: .github/badges
          generate-branches-badge: false
          jacoco-csv-file: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv
          generate-coverage-endpoint: true
          coverage-endpoint-filename: jacoco.json
      - name: PrintDir
        run: |
          ls .github/badges
      - name: PrintJson
        run: |
          cat .github/badges/jacoco.json
        #run: |
        #  JSON=$(cat .github/badges/jacoco.json)
        #  echo "::set-output name=matrix::${JSON//'%'/'%25'}"