name: UnitTest

on: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unitTest
        run: ./gradlew testDebugUnitTest
      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv
